from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import geocoder
import datetime


g = geocoder.ip("me")
currentLocation = g.city


def api(currentLocation):
    global measure, response_fah, response_cel, check
    querystring = {"contentType": "json"}
    measure = "us"
    response_fah = requests.request("GET", "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services"
                                           "/timeline/" + currentLocation + "?unitGroup=" + measure +
                                    "&key=BFM23YQMJHULDF6R3NZA4YUNB&include=fcst%2Calerts%2Ccurrent",
                                    params=querystring)

    measure = "uk"
    response_cel = requests.request("GET", "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services"
                                           "/timeline/" + currentLocation + "?unitGroup=" + measure +
                                    "&key=BFM23YQMJHULDF6R3NZA4YUNB&include=fcst%2Calerts%2Ccurrent",
                                    params=querystring)
    check = "us"
api(currentLocation)

def current():
    global location, c_temp_fah, c_temp_cel, alerts, measure, c_conditions, data_fah, data_cel

    data_fah = response_fah.json()
    data_cel = response_cel.json()

    weatherInfo_fah = data_fah["currentConditions"]
    weatherInfo_cel = data_cel["currentConditions"]

    c_temp_fah = str(round(weatherInfo_fah["temp"]))
    c_temp_cel = str(round(weatherInfo_cel["temp"]))

    location = data_fah["address"]

    c_conditions = weatherInfo_fah["conditions"]

    alerts = data_fah["alerts"]
    if len(alerts) == 0:
        alerts = "None at this time"
    else:
        alerts = data_fah["alerts"][0]["headline"]

current()


def weekConditions(x):
    condition = data_fah["days"][x]["conditions"]
    return condition


# QT Designer UI designer, converted to python code
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow.setMaximumSize(QtCore.QSize(500, 700))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 160, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 160, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 160, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 160, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.location = QtWidgets.QLabel(self.centralwidget)
        self.location.setGeometry(QtCore.QRect(0, 30, 500, 85))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(48)
        self.location.setFont(font)
        self.location.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.location.setScaledContents(True)
        self.location.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.location.setWordWrap(False)
        self.location.setObjectName("location")
        self.currentTemp = QtWidgets.QLabel(self.centralwidget)
        self.currentTemp.setGeometry(QtCore.QRect(0, 110, 500, 115))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(72)
        self.currentTemp.setFont(font)
        self.currentTemp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.currentTemp.setStyleSheet("")
        self.currentTemp.setScaledContents(True)
        self.currentTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.currentTemp.setObjectName("currentTemp")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 240, 500, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 615, 500, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 575, 500, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.alerts = QtWidgets.QLabel(self.centralwidget)
        self.alerts.setGeometry(QtCore.QRect(5, 585, 490, 40))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.alerts.setFont(font)
        self.alerts.setWordWrap(True)
        self.alerts.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.alerts.setObjectName("alerts")
        self.currentConditions = QtWidgets.QLabel(self.centralwidget)
        self.currentConditions.setGeometry(QtCore.QRect(0, 225, 500, 25))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.currentConditions.setFont(font)
        self.currentConditions.setScaledContents(True)
        self.currentConditions.setAlignment(QtCore.Qt.AlignCenter)
        self.currentConditions.setObjectName("currentConditions")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 250, 211, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.forecastConditions = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastConditions.setFont(font)
        self.forecastConditions.setObjectName("forecastConditions")
        self.verticalLayout_3.addWidget(self.forecastConditions)
        self.forecastConditions_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastConditions_2.setFont(font)
        self.forecastConditions_2.setObjectName("forecastConditions_2")
        self.verticalLayout_3.addWidget(self.forecastConditions_2)
        self.forecastConditions_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastConditions_3.setFont(font)
        self.forecastConditions_3.setObjectName("forecastConditions_3")
        self.verticalLayout_3.addWidget(self.forecastConditions_3)
        self.forecastConditions_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastConditions_4.setFont(font)
        self.forecastConditions_4.setObjectName("forecastConditions_4")
        self.verticalLayout_3.addWidget(self.forecastConditions_4)
        self.forecastConditions_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastConditions_5.setFont(font)
        self.forecastConditions_5.setObjectName("forecastConditions_5")
        self.verticalLayout_3.addWidget(self.forecastConditions_5)
        self.forecastConditions_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastConditions_6.setFont(font)
        self.forecastConditions_6.setObjectName("forecastConditions_6")
        self.verticalLayout_3.addWidget(self.forecastConditions_6)
        self.forecastConditions_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastConditions_7.setFont(font)
        self.forecastConditions_7.setObjectName("forecastConditions_7")
        self.verticalLayout_3.addWidget(self.forecastConditions_7)
        self.forecastConditions_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastConditions_8.setFont(font)
        self.forecastConditions_8.setObjectName("forecastConditions_8")
        self.verticalLayout_3.addWidget(self.forecastConditions_8)
        self.forecastConditions_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastConditions_9.setFont(font)
        self.forecastConditions_9.setObjectName("forecastConditions_9")
        self.verticalLayout_3.addWidget(self.forecastConditions_9)
        self.forecastConditions_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastConditions_10.setFont(font)
        self.forecastConditions_10.setObjectName("forecastConditions_10")
        self.verticalLayout_3.addWidget(self.forecastConditions_10)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(15, 250, 131, 331))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.forecastDay = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastDay.setFont(font)
        self.forecastDay.setObjectName("forecastDay")
        self.verticalLayout.addWidget(self.forecastDay)
        self.forecastDay_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastDay_2.setFont(font)
        self.forecastDay_2.setObjectName("forecastDay_2")
        self.verticalLayout.addWidget(self.forecastDay_2)
        self.forecastDay_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastDay_3.setFont(font)
        self.forecastDay_3.setObjectName("forecastDay_3")
        self.verticalLayout.addWidget(self.forecastDay_3)
        self.forecastDay_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastDay_4.setFont(font)
        self.forecastDay_4.setObjectName("forecastDay_4")
        self.verticalLayout.addWidget(self.forecastDay_4)
        self.forecastDay_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastDay_5.setFont(font)
        self.forecastDay_5.setObjectName("forecastDay_5")
        self.verticalLayout.addWidget(self.forecastDay_5)
        self.forecastDay_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastDay_6.setFont(font)
        self.forecastDay_6.setObjectName("forecastDay_6")
        self.verticalLayout.addWidget(self.forecastDay_6)
        self.forecastDay_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastDay_7.setFont(font)
        self.forecastDay_7.setObjectName("forecastDay_7")
        self.verticalLayout.addWidget(self.forecastDay_7)
        self.forecastDay_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastDay_8.setFont(font)
        self.forecastDay_8.setObjectName("forecastDay_8")
        self.verticalLayout.addWidget(self.forecastDay_8)
        self.forecastDay_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastDay_9.setFont(font)
        self.forecastDay_9.setObjectName("forecastDay_9")
        self.verticalLayout.addWidget(self.forecastDay_9)
        self.forecastDay_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.forecastDay_10.setFont(font)
        self.forecastDay_10.setObjectName("forecastDay_10")
        self.verticalLayout.addWidget(self.forecastDay_10)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(5, 640, 490, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tempButton = QtWidgets.QPushButton(self.splitter)
        self.searchButton = QtWidgets.QPushButton(self.splitter)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tempButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tempButton.setFont(font)
        self.tempButton.setToolTipDuration(0)
        self.tempButton.setAutoFillBackground(False)
        self.tempButton.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border: 0px solid rgb(0, 0, 0);\n"
                                      "    border-radius: 20px;\n"
                                      "    border-style: outset;\n"
                                      "    background: qradialgradient(\n"
                                      "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                      "        radius: 1.35, stop: 0 rgb(72, 115, 148), stop: 1 rgb(72, 115, 148)\n"
                                      "        );\n"
                                      "    padding: 5px;\n"
                                      "    }\n"
                                      "\n"
                                      "    \n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background: qradialgradient(\n"
                                      "        cx: 0.10, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                      "        radius: 1.35, stop: 0 rgb(124, 198, 255), stop: 1 rgb(124, 198, 255)\n"
                                      "        );\n"
                                      "    }\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    border-style: inset;\n"
                                      "    background: qradialgradient(\n"
                                      "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                      "        radius: 1.35, stop: 0 rgb(72, 115, 148), stop: 1 rgb(72, 115, 148)\n"
                                      "        );\n"
                                      "    }")
        self.tempButton.setAutoDefault(False)
        self.tempButton.setDefault(False)
        self.tempButton.setFlat(False)
        self.tempButton.setObjectName("tempButton")
        self.tempButton.clicked.connect(lambda: self.pushed())
        self.searchButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.searchButton.setFont(font)
        self.searchButton.setToolTipDuration(0)
        self.searchButton.setAutoFillBackground(False)
        self.searchButton.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border: 0px solid rgb(0, 0, 0);\n"
                                      "    border-radius: 20px;\n"
                                      "    border-style: outset;\n"
                                      "    background: qradialgradient(\n"
                                      "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                      "        radius: 1.35, stop: 0 rgb(72, 115, 148), stop: 1 rgb(72, 115, 148)\n"
                                      "        );\n"
                                      "    padding: 5px;\n"
                                      "    }\n"
                                      "\n"
                                      "    \n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background: qradialgradient(\n"
                                      "        cx: 0.10, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                      "        radius: 1.35, stop: 0 rgb(124, 198, 255), stop: 1 rgb(124, 198, 255)\n"
                                      "        );\n"
                                      "    }\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    border-style: inset;\n"
                                      "    background: qradialgradient(\n"
                                      "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                      "        radius: 1.35, stop: 0 rgb(72, 115, 148), stop: 1 rgb(72, 115, 148)\n"
                                      "        );\n"
                                      "    }")
        self.searchButton.setAutoDefault(False)
        self.searchButton.setDefault(False)
        self.searchButton.setFlat(False)
        self.searchButton.setObjectName("searchButton")
        self.searchButton.clicked.connect(lambda: self.search())
        self.locationInput = QtWidgets.QLineEdit(self.splitter)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QRadialGradient(0.3, -0.4, 1.35, 0.3, -0.4)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(72, 115, 148))
        gradient.setColorAt(1.0, QtGui.QColor(72, 115, 148))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.locationInput.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setBold(False)
        font.setWeight(50)
        self.locationInput.setFont(font)
        self.locationInput.setToolTipDuration(0)
        self.locationInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.locationInput.setStyleSheet("QLineEdit {\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border: 0px solid rgb(0, 0, 0);\n"
                                         "    border-radius: 20px;\n"
                                         "    border-style: outset;\n"
                                         "    background: qradialgradient(\n"
                                         "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                         "        radius: 1.35, stop: 0 rgb(72, 115, 148), stop: 1 rgb(72, 115, 148)\n"
                                         "        );\n"
                                         "    padding: 5px;\n"
                                         "    }\n"
                                         "\n"
                                         "    \n"
                                         "\n"
                                         "QLineEdit:hover {\n"
                                         "    background: qradialgradient(\n"
                                         "        cx: 0.10, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                         "        radius: 1.35, stop: 0 rgb(124, 198, 255), stop: 1 rgb(124, 198, 255)\n"
                                         "        );\n"
                                         "    }\n"
                                         "\n"
                                         "QLineEdit:pressed {\n"
                                         "    border-style: inset;\n"
                                         "    background: qradialgradient(\n"
                                         "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                         "        radius: 1.35, stop: 0 rgb(72, 115, 148), stop: 1 rgb(72, 115, 148)\n"
                                         "        );\n"
                                         "    }")
        self.locationInput.setText("")
        self.locationInput.setFrame(True)
        self.locationInput.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.locationInput.setAlignment(QtCore.Qt.AlignCenter)
        self.locationInput.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.locationInput.setClearButtonEnabled(False)
        self.locationInput.setObjectName("locationInput")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(175, 250, 141, 331))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.forecastTemp = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.forecastTemp.setFont(font)
        self.forecastTemp.setObjectName("forecastTemp")
        self.verticalLayout_2.addWidget(self.forecastTemp)
        self.forecastTemp_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.forecastTemp_2.setFont(font)
        self.forecastTemp_2.setObjectName("forecastTemp_2")
        self.verticalLayout_2.addWidget(self.forecastTemp_2)
        self.forecastTemp_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.forecastTemp_3.setFont(font)
        self.forecastTemp_3.setObjectName("forecastTemp_3")
        self.verticalLayout_2.addWidget(self.forecastTemp_3)
        self.forecastTemp_4 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.forecastTemp_4.setFont(font)
        self.forecastTemp_4.setObjectName("forecastTemp_4")
        self.verticalLayout_2.addWidget(self.forecastTemp_4)
        self.forecastTemp_5 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.forecastTemp_5.setFont(font)
        self.forecastTemp_5.setObjectName("forecastTemp_5")
        self.verticalLayout_2.addWidget(self.forecastTemp_5)
        self.forecastTemp_6 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.forecastTemp_6.setFont(font)
        self.forecastTemp_6.setObjectName("forecastTemp_6")
        self.verticalLayout_2.addWidget(self.forecastTemp_6)
        self.forecastTemp_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.forecastTemp_7.setFont(font)
        self.forecastTemp_7.setObjectName("forecastTemp_7")
        self.verticalLayout_2.addWidget(self.forecastTemp_7)
        self.forecastTemp_8 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.forecastTemp_8.setFont(font)
        self.forecastTemp_8.setObjectName("forecastTemp_8")
        self.verticalLayout_2.addWidget(self.forecastTemp_8)
        self.forecastTemp_10 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.forecastTemp_10.setFont(font)
        self.forecastTemp_10.setObjectName("forecastTemp_10")
        self.verticalLayout_2.addWidget(self.forecastTemp_10)
        self.forecastTemp_9 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.forecastTemp_9.setFont(font)
        self.forecastTemp_9.setObjectName("forecastTemp_9")
        self.verticalLayout_2.addWidget(self.forecastTemp_9)
        self.tempButton.raise_()
        self.locationInput.raise_()
        self.location.raise_()
        self.currentTemp.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.alerts.raise_()
        self.currentConditions.raise_()
        self.forecastDay.raise_()
        self.forecastDay_2.raise_()
        self.forecastDay_3.raise_()
        self.forecastDay_4.raise_()
        self.forecastDay_5.raise_()
        self.forecastDay_6.raise_()
        self.forecastDay_7.raise_()
        self.forecastDay_8.raise_()
        self.forecastDay_9.raise_()
        self.forecastDay_10.raise_()
        self.forecastTemp.raise_()
        self.forecastTemp_2.raise_()
        self.forecastTemp_3.raise_()
        self.forecastTemp_4.raise_()
        self.forecastTemp_5.raise_()
        self.forecastTemp_6.raise_()
        self.forecastTemp_7.raise_()
        self.forecastTemp_8.raise_()
        self.forecastTemp_9.raise_()
        self.forecastTemp_10.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        global _translate
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather App"))
        self.location.setText(_translate("MainWindow", location.title()))
        self.currentTemp.setText(_translate("MainWindow", c_temp_fah + "°F"))
        self.alerts.setText(_translate("MainWindow", "Alerts: " + alerts))
        self.currentConditions.setText(_translate("MainWindow", c_conditions))
        self.setConditions()
        self.forecastDay.setText(_translate("MainWindow", "Today"))
        self.forecastDay_2.setText(_translate("MainWindow", self.dayofweek(data_fah["days"][1]["datetime"])))
        self.forecastDay_3.setText(_translate("MainWindow", self.dayofweek(data_fah["days"][2]["datetime"])))
        self.forecastDay_4.setText(_translate("MainWindow", self.dayofweek(data_fah["days"][3]["datetime"])))
        self.forecastDay_5.setText(_translate("MainWindow", self.dayofweek(data_fah["days"][4]["datetime"])))
        self.forecastDay_6.setText(_translate("MainWindow", self.dayofweek(data_fah["days"][5]["datetime"])))
        self.forecastDay_7.setText(_translate("MainWindow", self.dayofweek(data_fah["days"][6]["datetime"])))
        self.forecastDay_8.setText(_translate("MainWindow", self.dayofweek(data_fah["days"][7]["datetime"])))
        self.forecastDay_9.setText(_translate("MainWindow", self.dayofweek(data_fah["days"][8]["datetime"])))
        self.forecastDay_10.setText(_translate("MainWindow", self.dayofweek(data_fah["days"][9]["datetime"])))
        self.tempButton.setText(_translate("MainWindow", "Fahrenheit/Celsius"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.locationInput.setPlaceholderText(_translate("MainWindow", "Enter a City"))
        self.setFah()


    def setFah(self):
        self.currentTemp.setText(_translate("MainWindow", c_temp_fah + "°F"))
        self.forecastTemp.setText(_translate("MainWindow", str(round(data_fah["days"][0]["temp"])) + "°F"))
        self.forecastTemp_2.setText(_translate("MainWindow", str(round(data_fah["days"][1]["temp"])) + "°F"))
        self.forecastTemp_3.setText(_translate("MainWindow", str(round(data_fah["days"][2]["temp"])) + "°F"))
        self.forecastTemp_4.setText(_translate("MainWindow", str(round(data_fah["days"][3]["temp"])) + "°F"))
        self.forecastTemp_5.setText(_translate("MainWindow", str(round(data_fah["days"][4]["temp"])) + "°F"))
        self.forecastTemp_6.setText(_translate("MainWindow", str(round(data_fah["days"][5]["temp"])) + "°F"))
        self.forecastTemp_7.setText(_translate("MainWindow", str(round(data_fah["days"][6]["temp"])) + "°F"))
        self.forecastTemp_8.setText(_translate("MainWindow", str(round(data_fah["days"][7]["temp"])) + "°F"))
        self.forecastTemp_9.setText(_translate("MainWindow", str(round(data_fah["days"][8]["temp"])) + "°F"))
        self.forecastTemp_10.setText(_translate("MainWindow", str(round(data_fah["days"][9]["temp"])) + "°F"))


    def setCel(self):
        self.currentTemp.setText(_translate("MainWindow", c_temp_cel + "°C"))
        self.forecastTemp.setText(_translate("MainWindow", str(round(data_cel["days"][0]["temp"])) + "°C"))
        self.forecastTemp_2.setText(_translate("MainWindow", str(round(data_cel["days"][1]["temp"])) + "°C"))
        self.forecastTemp_3.setText(_translate("MainWindow", str(round(data_cel["days"][2]["temp"])) + "°C"))
        self.forecastTemp_4.setText(_translate("MainWindow", str(round(data_cel["days"][3]["temp"])) + "°C"))
        self.forecastTemp_5.setText(_translate("MainWindow", str(round(data_cel["days"][4]["temp"])) + "°C"))
        self.forecastTemp_6.setText(_translate("MainWindow", str(round(data_cel["days"][5]["temp"])) + "°C"))
        self.forecastTemp_7.setText(_translate("MainWindow", str(round(data_cel["days"][6]["temp"])) + "°C"))
        self.forecastTemp_8.setText(_translate("MainWindow", str(round(data_cel["days"][7]["temp"])) + "°C"))
        self.forecastTemp_9.setText(_translate("MainWindow", str(round(data_cel["days"][8]["temp"])) + "°C"))
        self.forecastTemp_10.setText(_translate("MainWindow", str(round(data_cel["days"][9]["temp"])) + "°C"))


    def setConditions(self):
        self.forecastConditions.setText(_translate("MainWindow", weekConditions(0)))
        self.forecastConditions_2.setText(_translate("MainWindow", weekConditions(1)))
        self.forecastConditions_3.setText(_translate("MainWindow", weekConditions(2)))
        self.forecastConditions_4.setText(_translate("MainWindow", weekConditions(3)))
        self.forecastConditions_5.setText(_translate("MainWindow", weekConditions(4)))
        self.forecastConditions_6.setText(_translate("MainWindow", weekConditions(5)))
        self.forecastConditions_7.setText(_translate("MainWindow", weekConditions(6)))
        self.forecastConditions_8.setText(_translate("MainWindow", weekConditions(7)))
        self.forecastConditions_9.setText(_translate("MainWindow", weekConditions(8)))
        self.forecastConditions_10.setText(_translate("MainWindow", weekConditions(9)))


    def currentNew(self):
        self.location.setText(_translate("MainWindow", location.title()))
        self.alerts.setText(_translate("MainWindow", "Alerts: " + alerts))
        self.currentConditions.setText(_translate("MainWindow", c_conditions))


    def search(self):
        self.boxlocation = self.locationInput.text()
        if self.boxlocation == "":
            pass
        else:
            api(self.boxlocation)
            current()
            self.setFah()
            self.setConditions()
            self.currentNew()


    def pushed(self):
        global check
        if check == "us":
            check = "uk"
            self.setCel()
        else:
            check = "us"
            self.setFah()


    def dayofweek(self, forecastDate):
        date = datetime.datetime.strptime(forecastDate, "%Y-%m-%d")
        day = date.strftime('%A')
        return day



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
